# Site
repository: TildeWill/tildewill.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Will Read
title: Senior Software Generalist
email: will@sustainablemagic.com
website: wlr.sustainablemagic.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  TildeWill
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: willread
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Board Game Arena
  icon: fas fa-dice
  url: https://boardgamearena.com/player?id=94728286
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Will and I am an experienced senior software engineer, engineering leader, and an all around curious person. I have a demonstrated history of helping software teams shorten feedback loops, ship software, and stay happy. I can own critical business systems and lead strategic planning, roadmapping, and team planning. I believe small, empowered teams make employees happy and quality software products that delight users follows as a result. 


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 1942 Radio Modernization
        link: github.com/TildeWill/radio_project
        icon: fab fa-github
        # link_text: Project Website
#        additional_links:
#          - title:  Radio Project github repo
#            icon: fab fa-github
#            url: github.com/TildeWill/radio_project
        quote: >
          Something old made new again
        description: | 
          When my parents moved out of their house, they wanted to re-home [a radio from my great-grandparent's generation](https://www.radiomuseum.org/r/belmont_582_ch_series_b.html){:target="_blank"}. For a time before TVs, this radio was the centerpiece of family entertainment. However, time hadn't been kind; the power cord was fraying and the tuner didn't work. My step daughter decided to open it up and get it working again. We removed the guts, reattached the tuner and soon had a functional, but impractical AM-only radio. We decided to honor the legacy of the radio as a centerpiece by refurbishing the case, updating the inside to support Bluetooth connections and FM bandwidths using the Arduino prototyping platform, and adding a bit of visual amusement with some ferrofluid. 
          
          This project taught me a lot about hardware components including Serial Peripheral Interfaces (SPI), Bluetooth protocols, power supplies and voltages. I also practiced my skills at case making and mounting components in a way that is durable enough to withstand human interactions. All along the way passing as much of my knowledge and learnings on to my ten year old step daughter as we worked together. 

      - layout: top-middle
        title: Reteamer
        link: github.com/Reteamer/reteamer
        icon: fab fa-github
#        link_text: Application Website

        quote: >
          How can I plan for staffing changes on modern software teams?
        description: | 
          At Pivotal Labs, we had an in-house tool specifically for the frequent cross team rotation we valued in our practice. Since leaving Pivotal, I longed to have that tool to plan for changes in the teams I was leading. In 2022 I set out to solve that problem, and built an application called Reteamer. I designed it using the organizational principles described in Heidi Helfand's book, [_Dynamic Reteaming_](https://www.heidihelfand.com/dynamic-reteaming/){:target="_blank"}. I also built a new database ORM for Rails called (furcate)[https://github.com/TildeWill/furcate]{:target="_blank"} which added the ability to "fork" a set of data in a database, treating it much like a git repo for collaboration.
          
          Through this project, I learned a lot about data structure and storage, event logging, and bitemporal data modeling. It was also a great chance for me to spin up my third business - I have previously started a sport fencing club and a company around the (Hugin automation project](https://github.com/huginn/huginn){:target="_blank"}. Ultimately, Reteamer was shelved after gathering customer feedback on the prototype. People allocations touches many other systems including identity, payroll, billing and financial forecasting, time cards, and more. Building those integrations was beyond the scope of what the company could do with a handful of employees.

      - layout: top-middle
        title: Mechanical Keyboard Journey
        link: https://github.com/brickbots/chocV
        link_text: The ChocV Keyboard by BrickBots
        quote: >
          Starting from zero with a growth mindset
        description: |
          I have a somewhat absurd dream of having a keyboard-like input device incorporated in to my pants so I can sit down and interact with any device in front of me from a desktop to a phone or streaming service on a TV that necessitates I type out my email address and password using arrow keys only. More practically, I wanted to improve my soldering skills and I knew from the radio project that I had a lot of room to grow there.  
          
          I came across the ChocV keyboard an fell in love with the low profile, compact size, ortholinear key layout, and simple design. It is a 36-key keyboard and instead of the traditional QWERTY layout uses a layout called [Miryoku by Manna Harbour](https://github.com/manna-harbour/miryoku){:target="_blank"}. It also incorporates six "layers" (think of a layer like your shift key which gives you a whole new set of characters), and through all this it keeps my fingers on the home row more than I could have ever imagined. Even with the well documented repo of the ChocV I still needed to learn a lot about mechanical keyboards, and for that I turned to an old colleague who was known for having a custom mechanical keyboard or "keeb" as they're often called. Through him I learned about the switches - clicky, tactile, linear, silent - and keycaps of which there are a lot, membranes, firmware frameworks, vendors that might be able to sell me what I need, and forums where I might find more help. I got a lot of help from the ChocV creator too when it came time to flash the firmware and debug my work. I ended up writing about how [this project really took a community to bootstrap my knowledge](https://www.linkedin.com/posts/willread_i-built-a-keyboard-but-that-is-a-lie-when-activity-7120579022039719936-q5lh?utm_source=share&utm_medium=member_desktop){:target="_blank"}.  
          
          In the end I have a functioning keyboard that's pretty easy to travel with. I not only upped my solder game but I also learned how to use solder paste to connect surface mount devices (SMD). While this rigid, unibody keyboard won't address my dreams of keyboard pants, I do plan to take the next step and build a [Stront](https://github.com/zzeneg/stront){:target="_blank"} which will teach me about split keyboards and will incorporate extra inputs like a track pad and scroll wheels. After that, maybe it'll be flexible PCBs, [incorporating magnets](https://evantravers.com/articles/2023/04/06/magsafe-tenting-and-wearable-keyboards/){:target="_blank"}, or looking into e-textile techniques to sew soft switches into my leg wear. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Board Gaming (Wingspan, Catan, Heat, Power Grid)
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
