# Site
repository: TildeWill/tildewill.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Will Read
title: Senior Software Generalist
email: will@sustainablemagic.com
website: wlr.sustainablemagic.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  TildeWill
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: willread
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Board Game Arena
  icon: fas fa-dice
  url: https://boardgamearena.com/player?id=94728286
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Will and I am an experienced senior software engineer, engineering leader, and an all around curious person. I have a demonstrated history of helping software teams shorten feedback loops, ship software, and stay happy. I can own critical business systems and lead strategic planning, roadmapping, and team planning. I believe small, empowered teams make employees happy and quality software products that delight users follows as a result. 


content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 1942 Radio Modernization
        link: github.com/TildeWill/radio_project
        # link_text: Project Website
        additional_links:
          - title:  Radio Project github repo
            icon: fab fa-github
            url: github.com/TildeWill/radio_project
        quote: >
          Something old made new again
        description: | 
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
          
          This project taught me a lot about hardware components including Serial Peripheral Interfaces (SPI), Bluetooth protocols, power supplies and voltages. I also practiced my skills at case making and mounting components in a way that is durable enough to withstand human interactions. All along the way passing as much of my knowledge and learnings on to my ten year old step daughter as we worked together. 

      - layout: top-middle
        title: Reteamer
        link: github.com/Reteamer/reteamer
        link_text: Project Website

        quote: >
          How can I plan for staffing changes on modern software teams?
        description: | 
          At Pivotal Labs, we had an in-house tool specifically for the frequent cross team rotation we valued in our practice. Since leaving Pivotal, I longed to have that tool to plan for changes in the teams I was leading. In 2022 I set out to solve that problem, and built an application called Reteamer. I designed it using the organizational principles described in Heidi Helfand's book, [_Dynamic Reteaming_](https://www.heidihelfand.com/dynamic-reteaming/). I also built a new database ORM for Rails called (furcate)[https://github.com/TildeWill/furcate] which added the ability to "fork" a set of data in a database, treating it much like a git repo for collaboration.
          
          Through this project, I learned a lot about data structure and storage, event logging, and bitemporal data modeling. It was also a great chance for me to spin up my third business - I have previously started a sport fencing club and a company around the (Hugin automation project](https://github.com/huginn/huginn). Ultimately, Reteamer was shelved after gathering customer feedback on the prototype. People allocations touches many other systems including identity, payroll, billing and financial forecasting, time cards, and more. Building those integrations was beyond the scope of what the company could do with a handful of employees.  

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Board Gaming (Wingspan, Catan, Heat, Power Grid)
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
